Add readme.md
courses-ionio/thesis pull request #32
Opened 2018-01-25 19:14 UTC by geopala

2018-02-01 08:31 UTC, mkamgit commented
Πρόσθεσε Ονοματεπώνυμο και ΑΜ στην αναφορά σου. Επίσης, δώσε μία εικόνα για το που βρίσκεσαι αναφορικά με το χρονοδιάγραμμα και γράψε τι έχεις κάνει σε κάθε στάδιο. Αν σε βοηθάει, υπάρχει σχετικό υπόδειγμα: https://github.com/courses-ionio/thesis/tree/master/current/2003003.

2018-02-03 15:52 UTC, mkamgit requested changes
Πρόσθεσε Ονοματεπώνυμο και ΑΜ στην αναφορά σου. Επίσης, δώσε μία εικόνα για το που βρίσκεσαι αναφορικά με το χρονοδιάγραμμα και γράψε τι έχεις κάνει σε κάθε στάδιο. Αν σε βοηθάει, υπάρχει σχετικό υπόδειγμα: https://github.com/courses-ionio/thesis/tree/master/current/2003003.

2018-02-03 18:32 UTC, bgarnb reviewed
Χρειάζεται να προσθέσεις ΑΜ και ονοματεπώνυμο. Πολύ σωστά περιγράφεις το σύστημα που θα τροποποιήσεις και τι σκοπεύεις να κάνεις. Κάποιες ενδεικτικές οθόνες όμως από την αρχική εγκατάσταση του συστήματος και κάποια σχόλια για το στάδιο στο οποίο βρίσκεσαι τώρα θα ήταν χρήσιμα για να περιγράψουν τη δουλειά σου.

2018-02-03 18:48 UTC, epidrome commented
@mkamgit @geopala υπάρχει πλέον και πλούσιο υπόδειγμα με περιεχόμενο σε εξέλιξη:
https://github.com/courses-ionio/thesis/tree/master/current/2014221

@bgarnb θα πρέπει να βάλετε και μια ένδειξη δεκτό-αλλαγές-άκυρο ώστε ο συντονιστής της πτυχιακής @mkamgit  να αποφασίσει αν θα κάνει δεκτό το αίτημα ή θα πρέπει να γίνουν αλλαγές

2018-02-03 19:01 UTC, bgarnb requested changes
Χρειάζεται να προσθέσεις ΑΜ και ονοματεπώνυμο. Πολύ σωστά περιγράφεις το σύστημα που θα τροποποιήσεις και τι σκοπεύεις να κάνεις. Κάποιες ενδεικτικές οθόνες όμως από την αρχική εγκατάσταση του συστήματος και κάποια σχόλια για το στάδιο στο οποίο βρίσκεσαι τώρα θα ήταν χρήσιμα για να περιγράψουν τη δουλειά σου.

2018-02-04 19:55 UTC, diogenisAl commented
@geopala Επίσης, καλό θα ήταν να φτιάξεις ένα πρόχειρο προσχέδιο (π.χ. στο χαρτί) σχετικά με το πώς σκέφτεσαι να είναι το νέο layout της εφαρμογής.
Το εν λόγω προσχέδιο θα πρέπει να συμπεριληφθεί στο παραδοτέο.

2018-02-04 19:57 UTC, diogenisAl requested changes
Επίσης, καλό θα ήταν να φτιάξεις ένα πρόχειρο προσχέδιο (π.χ. στο χαρτί) σχετικά με το πώς σκέφτεσαι να είναι το νέο layout της εφαρμογής.
Το εν λόγω προσχέδιο θα πρέπει να συμπεριληφθεί στο παραδοτέο.

2018-02-05 07:25 UTC, epidrome commented
@geopala 
επειδή δεν έχω κάπου πρόσβαση στο ιδιωτικό σου αποθετήριο γράφω εδώ μερικά σχόλια για τις προδιαγραφές σου:

1. η ελληνική γλώσσα θα πρέπει να υλοποιηθεί με τρόπο γενικό, δλδ η υλοποίηση θα μπορεί να δεχτεί οποιαδήποτε γλώσσα (π.χ., ισπανικά), αρκεί φυσικά να γίνει ντέμο με την ελληνική

2. θα πρέπει να εξεταστεί το ενδεχόμενο μεταφοράς του συστήματος σε άλλη πιο μοντέρνα υποδομή, π.χ.python, nodejs, etc

3. στην διεπαφή της εφαρμογής θα πρέπει να προστεθεί μια χρονική διάσταση που να επιτρέπει στον χρήση να δει το φαινόμενο τις προηγούμενες εβδομάδες-μήνες

4. στην οπτικοποίηση των δεδομένων θα πρέπει να δοκιμαστούν νέες εναλλακτικές, όπως heatmap, γιατί τα πινς όταν είναι πολλά χάνουν το νόημα τους

2018-02-05 13:06 UTC, epidrome commented
@geopala 
γενικά φαίνεται πως δεν έχεις ακολουθήσει τις οδηγίες για δημιουργία ιδιωτικού αποθετηρίου κτλ:
https://github.com/courses-ionio/thesis/wiki
οπότε κλείνουμε προσωρινά το αίτημα σου μεχρι να ακολουθήσεις τις οδηγίες
για τον συντονισμό της εργασίας σου κάλεσε εμένα (epidrome) και @mkamgit στο ιδιωτικό σου.

2018-02-05 13:06 UTC, closed without merging