Anafora_Prwtou_Paradoteou.md
courses-ionio/thesis pull request #33
Opened 2018-01-27 14:41 UTC by kostasartKKM

Γειά σας,

Μου ζητήθηκε να κάνω pull-request στο κεντρικό repository των πτυχιακών, με την αναφορά προόδου μου για το πρώτο παραδοτέο.

2018-01-30 12:25 UTC, epidrome reviewed
Αντί για το λινκ προς ένα ιδιωτικό αποθετήριο που δεν φαίνεται, μπορείς να προσθέσεις μερικές ενδεικτικές οθόνες? π.χ, μια για κάθε ένα από τα σημεία που αναφέρεις: αρχικός σχεδιασμός, προδιαγραφές, κτλ

επίσης, για να μπορέσουν οι αξιολογητές να καταλάβουν την συνολική εικόνα και να πουν την γνώμη τους, επειδή είναι το πρώτο παραδοτέο που στέλνεις θα πρέπει να συνοδεύεται και από κάποια αρχική περιγραφή-στόχο καθώς και το χρονοδιάγραμμα, υπάρχει υπόδειγμα αν βοηθάει
https://github.com/courses-ionio/thesis/tree/master/current/2003003

2018-01-30 12:59 UTC, kostasartKKM commented
Καλησπέρα,

Τέλεια, θα το επεξεργαστώ ώστε να περιλαμβάνει ενδεικτικές οθόνες κτλ. και μάλλον θα χρησιμοποιήσω και το υπόδειγμα.

Ευχαριστώ!

2018-01-31 02:32 UTC, kostasartKKM commented
Καλημέρα,

Έκανα τις αλλαγές στο Readme.md της αναφοράς σύμφωνα με το υπόδειγμα.
Πρόσθεσα εικόνες και το ανάλογο κείμενο για κάθε παραδοτέο (δεν έβαλα τα πρώτα drafts γιατί θα προέκυπτε κάτι πολύ μεγάλο). 

Την αλλαγή την έχει εμφανίσει ώς extra commit οπότε φαντάζομαι δεν χρειάζεται να κάνω κάποιο καινούργιο pull request.

Ευχαριστώ!

2018-01-31 08:45 UTC, epidrome requested changes
μπορείς να προσθέσεις μερικές δημόσιες ενδεικτικές οθόνες? π.χ, στο imgur, μια για κάθε ένα από τα σημεία που αναφέρεις: αρχικός σχεδιασμός, προδιαγραφές, κτλ 2-3 εικόνες που να έχουν και μια λεζάντα μέσα στα []

2018-01-31 13:06 UTC, kostasartKKM commented
Καλημέρα,

Sorry νόμιζα τις εικόνες θα τις εμφάνιζε.
Θα τις ανεβάσω στο imgur και θα αλλάξω τα Links.

Ευχαριστώ!

2018-01-31 14:05 UTC, kostasartKKM commented
Ok, άλλαξα τα links των εικόνων με καινούργια δημόσια απο το imgur(με την επιλογή για Markdown) και πρέπει οι εικόνες να εμφανίζονται κανονικά τώρα.

2018-01-31 14:10 UTC, epidrome approved these changes
μπράβο!
ΟΚ από εμένα ας δούμε τώρα και τα σχόλια των αξιολογητών πριν γίνει η ενσωμάτωση στο κεντρικό.

2018-02-01 17:27 UTC, merkourisa reviewed
Φαίνεται εξαιρετική δουλειά. 
Δεν έχω κάποιο συγκεκριμένο σχόλιο, ίσως κάποια από τα πιθανά προβλήματα να μπορούσες να τα αντιμετωπίσεις με αυτό: https://developer.vuforia.com/forum/qcar-api/unified-coordinate-system 

Μπορεί να σου φανούν χρήσιμα και τα εξής paper
[42. Largibles Large Tangible Interaction in Mobile Augmented Reality.pdf](https://github.com/courses-ionio/thesis/files/1686509/42.Largibles.Large.Tangible.Interaction.in.Mobile.Augmented.Reality.pdf)
[30. Code Bits An Inexpensive Tangible Computational Thinking Toolkit For K-12 Curriculum.pdf](https://github.com/courses-ionio/thesis/files/1686512/30.Code.Bits.An.Inexpensive.Tangible.Computational.Thinking.Toolkit.For.K-12.Curriculum.pdf)

Καλή συνέχεια και αναμένουμε τα επόμενα παραδοτέα με ενδιαφέρον.

2018-02-02 00:18 UTC, kostasartKKM commented
Ευχαριστώ!!

Τέλεια, θα τσεκάρω το link και τα paper.

Καλό βράδυ.

2018-02-03 18:09 UTC, bgarnb commented
Μπράβο Κώστα, πολύ καλή δουλειά

2018-02-03 18:13 UTC, bgarnb approved these changes

2018-02-03 18:22 UTC, kostasartKKM commented
Ευχαριστώ πολύ!!

2018-02-03 18:34 UTC, epidrome commented
@bgarnb @merkourisa @diogenisAl @c15pati @mkamgit 
ας κρατήσουμε αυτήν την αναφορά προόδου ως ενδεικτική και για τις άλλες πτυχιακές που επιβλέπει η ομάδα

2018-02-03 18:34 UTC, merged